server.port=10880
spring.application.name=exchange-counter

# Aeron Cluster Client
laser.cluster.client.base-dir=/Users/dawanyezhi/temp/aeron/client
laser.cluster.client.ingress-endpoints=0=localhost:9000,1=localhost:9001,2=localhost:9002
laser.cluster.client.egress-channel=aeron:udp?endpoint=localhost:0
laser.cluster.client.node-count=3

# Batch Order Defaults
laser.batch.default-rate=100
laser.batch.default-symbol-code=1

# 服务端mdc配置
laser.matching.result-broadcast.host=localhost
laser.matching.result-broadcast.base-port=40456
laser.matching.result-broadcast.node-count=3
laser.matching.result-broadcast.subscriber-base-port=40500
laser.matching.result-broadcast.stream-id=1002
laser.matching.result-broadcast.subscribe-enabled=true
