spring.application.name=exchange-result-publisher

laser.result-publisher.enabled=true
laser.result-publisher.node-id=0
laser.result-publisher.base-dir=/Users/dawanyezhi/temp/aeron
laser.result-publisher.channel-prefix=aeron:udp?endpoint=localhost:
laser.result-publisher.archive-control-port-base=8010
laser.result-publisher.result-channel=aeron:ipc
laser.result-publisher.result-stream-id=1001
laser.result-publisher.replay-channel=aeron:ipc
laser.result-publisher.replay-stream-id=1101
laser.result-publisher.fragment-limit=100
laser.result-publisher.idle-spin-limit=10000
laser.result-publisher.idle-max-spins=10
laser.result-publisher.idle-max-yields=20
laser.result-publisher.idle-min-park-ns=1000
laser.result-publisher.idle-max-park-ns=1000000
laser.result-publisher.start-position=0
laser.result-publisher.retry-interval-ms=1000
laser.result-publisher.retry-max-interval-ms=30000
laser.result-publisher.initial-connect-timeout-ms=30000
laser.result-publisher.archive-message-timeout-ms=3000
laser.result-publisher.aeron-driver-timeout-ms=3000
laser.result-publisher.publisher-type=logging
